import sys; print('Python %s on %s' % (sys.version, sys.platform))
/opt/conda/envs/fl1/bin/python /opt/pycharm/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 37893 --file /home/user/Documents/rotation1/ISTA_Rotation_1/flwr_test/flower_1.py
Connected to pydev debugger (build 232.10072.31)
/opt/conda/envs/fl1/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Files already downloaded and verified
Files already downloaded and verified
INFO flwr 2023-10-23 11:36:17,008 | app.py:175 | Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
2023-10-23 11:36:19,065	INFO worker.py:1621 -- Started a local Ray instance.
INFO flwr 2023-10-23 11:36:20,258 | app.py:210 | Flower VCE: Ray initialized with resources: {'object_store_memory': 2770400870.0, 'memory': 5540801742.0, 'node:__internal_head__': 1.0, 'CPU': 12.0, 'node:10.43.6.128': 1.0}
INFO flwr 2023-10-23 11:36:20,258 | app.py:218 | No `client_resources` specified. Using minimal resources for clients.
INFO flwr 2023-10-23 11:36:20,258 | app.py:224 | Flower VCE: Resources for each Virtual Client: {'num_cpus': 1, 'num_gpus': 0.0}
INFO flwr 2023-10-23 11:36:20,301 | app.py:270 | Flower VCE: Creating VirtualClientEngineActorPool with 12 actors
INFO flwr 2023-10-23 11:36:20,302 | my_server.py:45 | Initializing global parameters
INFO flwr 2023-10-23 11:36:20,302 | server.py:276 | Requesting initial parameters from one random client
(DefaultActor pid=60592) /opt/conda/envs/fl1/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
(DefaultActor pid=60592)   warn(
INFO flwr 2023-10-23 11:36:23,398 | server.py:280 | Received initial parameters from one random client
INFO flwr 2023-10-23 11:36:23,398 | my_server.py:47 | Evaluating initial parameters
INFO flwr 2023-10-23 11:36:23,398 | my_server.py:60 | FL starting
DEBUG flwr 2023-10-23 11:36:23,399 | server.py:222 | fit_round 1: strategy sampled 90 clients (out of 90)
(DefaultActor pid=60590) /opt/conda/envs/fl1/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source? [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(DefaultActor pid=60590)   warn( [repeated 2x across cluster]
(DefaultActor pid=60585) /opt/conda/envs/fl1/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source? [repeated 4x across cluster]
(DefaultActor pid=60585)   warn( [repeated 4x across cluster]
(DefaultActor pid=60582) /opt/conda/envs/fl1/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'libc10_cuda.so: cannot open shared object file: No such file or directory'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source? [repeated 3x across cluster]
(DefaultActor pid=60582)   warn( [repeated 3x across cluster]
DEBUG flwr 2023-10-23 11:38:14,978 | server.py:236 | fit_round 1 received 90 results and 0 failures
WARNING flwr 2023-10-23 11:38:15,055 | fedavg.py:242 | No fit_metrics_aggregation_fn provided
DEBUG flwr 2023-10-23 11:38:15,063 | server.py:173 | evaluate_round 1: strategy sampled 90 clients (out of 90)
Saving round 1 aggregated_parameters...
DEBUG flwr 2023-10-23 11:39:53,977 | server.py:187 | evaluate_round 1 received 90 results and 0 failures
DEBUG flwr 2023-10-23 11:39:53,978 | server.py:222 | fit_round 2: strategy sampled 90 clients (out of 90)
evaluate_metrics_fed: {'accuracy': 0.9278787878787883}
DEBUG flwr 2023-10-23 11:41:46,014 | server.py:236 | fit_round 2 received 90 results and 0 failures
Saving round 2 aggregated_parameters...
DEBUG flwr 2023-10-23 11:41:46,111 | server.py:173 | evaluate_round 2: strategy sampled 90 clients (out of 90)
DEBUG flwr 2023-10-23 11:43:31,068 | server.py:187 | evaluate_round 2 received 90 results and 0 failures
DEBUG flwr 2023-10-23 11:43:31,069 | server.py:222 | fit_round 3: strategy sampled 90 clients (out of 90)
evaluate_metrics_fed: {'accuracy': 0.9284848484848486}
DEBUG flwr 2023-10-23 11:45:15,097 | server.py:236 | fit_round 3 received 90 results and 0 failures
Saving round 3 aggregated_parameters...
DEBUG flwr 2023-10-23 11:45:15,167 | server.py:173 | evaluate_round 3: strategy sampled 90 clients (out of 90)
DEBUG flwr 2023-10-23 11:46:56,080 | server.py:187 | evaluate_round 3 received 90 results and 0 failures
DEBUG flwr 2023-10-23 11:46:56,080 | server.py:222 | fit_round 4: strategy sampled 90 clients (out of 90)
evaluate_metrics_fed: {'accuracy': 0.92969696969697}
DEBUG flwr 2023-10-23 11:48:40,812 | server.py:236 | fit_round 4 received 90 results and 0 failures
Saving round 4 aggregated_parameters...
DEBUG flwr 2023-10-23 11:48:40,943 | server.py:173 | evaluate_round 4: strategy sampled 90 clients (out of 90)
DEBUG flwr 2023-10-23 11:50:18,955 | server.py:187 | evaluate_round 4 received 90 results and 0 failures
DEBUG flwr 2023-10-23 11:50:18,956 | server.py:222 | fit_round 5: strategy sampled 90 clients (out of 90)
evaluate_metrics_fed: {'accuracy': 0.9294949494949497}
DEBUG flwr 2023-10-23 11:52:10,137 | server.py:236 | fit_round 5 received 90 results and 0 failures
Saving round 5 aggregated_parameters...
DEBUG flwr 2023-10-23 11:52:10,226 | server.py:173 | evaluate_round 5: strategy sampled 90 clients (out of 90)
DEBUG flwr 2023-10-23 11:53:46,919 | server.py:187 | evaluate_round 5 received 90 results and 0 failures
DEBUG flwr 2023-10-23 11:53:46,919 | server.py:222 | fit_round 6: strategy sampled 90 clients (out of 90)
evaluate_metrics_fed: {'accuracy': 0.9298989898989902}
DEBUG flwr 2023-10-23 11:55:25,584 | server.py:236 | fit_round 6 received 90 results and 0 failures
Saving round 6 aggregated_parameters...
DEBUG flwr 2023-10-23 11:55:25,669 | server.py:173 | evaluate_round 6: strategy sampled 90 clients (out of 90)
DEBUG flwr 2023-10-23 11:57:07,147 | server.py:187 | evaluate_round 6 received 90 results and 0 failures
DEBUG flwr 2023-10-23 11:57:07,147 | server.py:222 | fit_round 7: strategy sampled 90 clients (out of 90)
evaluate_metrics_fed: {'accuracy': 0.9300000000000002}
DEBUG flwr 2023-10-23 11:58:50,087 | server.py:236 | fit_round 7 received 90 results and 0 failures
Saving round 7 aggregated_parameters...
DEBUG flwr 2023-10-23 11:58:50,167 | server.py:173 | evaluate_round 7: strategy sampled 90 clients (out of 90)
DEBUG flwr 2023-10-23 12:00:27,098 | server.py:187 | evaluate_round 7 received 90 results and 0 failures
DEBUG flwr 2023-10-23 12:00:27,099 | server.py:222 | fit_round 8: strategy sampled 90 clients (out of 90)
evaluate_metrics_fed: {'accuracy': 0.9305050505050514}
DEBUG flwr 2023-10-23 12:02:05,379 | server.py:236 | fit_round 8 received 90 results and 0 failures
Saving round 8 aggregated_parameters...
DEBUG flwr 2023-10-23 12:02:05,458 | server.py:173 | evaluate_round 8: strategy sampled 90 clients (out of 90)
